export enum PostsActionsType {
  GET_POSTS = 'GET_POSTS',
  GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS',
  GET_POSTS_ERROR = 'GET_POSTS_ERROR',
  SELECT_POST = 'SELECT_POST',
  TOGGLE_AS_FAVORITE = 'TOGGLE_AS_FAVORITE',
  DELETE_POST = 'DELETE_POST',
  DELETE_ALL_POSTS = 'DELETE_ALL_POSTS',
}